name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Google Container Registry
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${GCP_SA_KEY}" | docker login -u _json_key --password-stdin https://gcr.io

    - name: Build and push Docker image
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
      run: |
        docker build . -t gcr.io/${{ env.GCP_PROJECT }}/JLR-interview/my-app:${{ github.sha }}
        docker push gcr.io/${{ env.GCP_PROJECT }}/JLR-interview/my-app:${{ github.sha }}
